import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../../contexts/AuthContext';
import { Button } from '../../components/common/Button';
import { Input } from '../../components/common/Input';
import { KeyRound, ShieldAlert, ArrowLeft } from 'lucide-react';

export const MfaVerification: React.FC = () => {
  const navigate = useNavigate();
  const { verifyMfa, pendingMfaEmail, isLoading } = useAuth();
  const [code, setCode] = useState('');
  const [error, setError] = useState<string | null>(null);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError(null);
    try {
      await verifyMfa(code);
      navigate('/app/dashboard');
    } catch (err: any) {
      setError(err.message || 'Invalid verification code');
    }
  };

  return (
    <div className="w-full">
      <div className="mb-6">
        <div className="inline-flex rounded-full bg-blue-500/10 p-2.5 text-blue-400 mb-3 border border-blue-500/20">
          <KeyRound className="h-6 w-6" />
        </div>
        <h2 className="text-2xl font-bold text-white tracking-tight">Two-Factor Verification</h2>
        <p className="mt-1 text-xs text-slate-400 leading-relaxed">
          Please enter the 6-digit authentication token generated by your authenticator app for{' '}
          <strong className="text-slate-200">{pendingMfaEmail || 'your account'}</strong>.
        </p>
      </div>

      {error && (
        <div className="mb-4 rounded-lg border border-red-500/30 bg-red-500/10 p-3 text-xs text-red-400">
          {error}
        </div>
      )}

      <form onSubmit={handleSubmit} className="space-y-4">
        <Input
          label="Verification Code"
          type="text"
          maxLength={6}
          required
          autoFocus
          value={code}
          onChange={(e) => setCode(e.target.value.replace(/\D/g, ''))}
          placeholder="e.g. 694021"
          className="text-center font-mono text-lg tracking-widest"
        />

        <Button type="submit" className="w-full" isLoading={isLoading}>
          Verify & Sign In
        </Button>

        <button
          type="button"
          onClick={() => navigate('/auth/login')}
          className="w-full flex items-center justify-center gap-1.5 text-xs text-slate-400 hover:text-white transition-colors pt-2 cursor-pointer"
        >
          <ArrowLeft className="h-3.5 w-3.5" />
          Back to standard login
        </button>
      </form>
    </div>
  );
};
